<?php
/**
 * Created by David Contavalli <david.contavalli@gmail.com>
 */
?>
<script type="text/ng-template" id="commentForm.html">
        <div class="modal-header">
            <h3 class="modal-title">Aggiungi un commento</h3>
        </div>
        <div class="modal-body">
            <div class="form-group">
                <input class="form-control" ng-model="name" name="name" value="" required>

                <p ng-show="commentForm.name.$invalid && !commentForm.name.$pristine" class="help-block">Campo
                    richiesto</p>
            </div>
            <div class="form-group">
                <input class="form-control" ng-model="lastName" name="lastName" value="" required>

                <p ng-show="commentForm.lastName.$invalid && !commentForm.lastName.$pristine" class="help-block">Campo
                    richiesto</p>
            </div>
            <div class="form-group">
                <select name="beach" ng-model="beach" required>
                    <option value="">Seleziona una spiaggia</option>
                    <option ng-repeat="beach in beaches" value="{( beach.id )}">
                        {( beach.name )} <span>({( beach.city )})</span>
                    </option>
                </select>

                <p ng-show="commentForm.beach.$invalid && !commentForm.beach.$pristine" class="help-block">Campo
                    richiesto</p>
            </div>
            <div class="form-group">
                <textarea class="form-control" ng-model="description" required ng-maxlength="255"
                          name="description"></textarea>

                <p ng-show="commentForm.description.$invalid && !commentForm.decription.$pristine" class="help-block">
                    Campo richiesto</p>

            </div>
            <div class="form-group">
                <input type="file" ngf-select name="commentImage" ng-model="commentImage">
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" ng-click="save(commentImage)">Save</button>
            <button class="btn btn-warning" ng-click="cancel()">Cancel</button>
        </div>
    </form>
</script>
</body>
