<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Dream beach API blueprint'); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('js/dist/bootstrap/dist/css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('js/dist/bootstrap/dist/css/bootstrap.min.css')) ?>


</head>
<body ng-app="dream-beach" ng-controller="CommentController">
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="col-lg-offset-4 col-lg-2">
            <form id="search_comment">
                <div class="form-group">
                    <select class="form-control" ng-change="filterByCity()" ng-model="cityOption" >
                        <option value="">Sceglia una citta'</option>
                        <option ng-repeat="city in cities" value="{( city.id )}">{( city.name )}</option>
                    </select>
                </div>
            </form>
        </div>
    </div>
</nav>
<div class="container">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies
            Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div>
<?php
echo $this->headScript()
    ->prependFile($this->basePath('js/dist/angular-resource/angular-resource.js'))
    ->prependFile($this->basePath('js/dist/angular-route/angular-route.js'))
    ->prependFile($this->basePath('js/app/app.js'))
    ->prependFile($this->basePath('js/Config.js'))
    ->prependFile($this->basePath('js/dist/angular/angular.js'))
    ->appendFile($this->basePath('js/app/Service/CommentResource.js'))
    ->appendFile($this->basePath('js/app/Service/CityResource.js'))
    ->appendFile($this->basePath('js/app/Controller/CommentController.js'));
?>
</body>
</html>
