<?php

namespace API\Entity\Repository;
use API\Entity\Beach;

/**
 * BeachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeachRepository extends \Doctrine\ORM\EntityRepository
{

    public function addBeach(Beach $beach)
    {
        $this->_em->persist($beach);
    }
}
