<?php

namespace API\Entity\Repository;
use API\Entity\Comment;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function addComment(Comment $comment)
    {
        $this->_em->persist($comment);
    }
}
