<?php

namespace API\Entity\Repository;

use API\Entity\Comment;
use Zend\Stdlib\Parameters;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function addComment(Comment $comment)
    {
        $this->_em->persist($comment);
    }

    public function getComments(Parameters $params)
    {

        $dql = 'SELECT co ' .
            'FROM ' . $this->_entityName . ' co ' .
            'JOIN co.beach b ' .
            'JOIN b.city c';

        $result = $this->_em->createQuery($dql)
            ->getResult();

        return $result;
    }
}
