<div class="content">
    <div ng-repeat="comment in comments | orderBy:'creationDate':false" class="col-lg-offset-2 col-lg-8 comment">
        <div class="col-lg-3">
            <img ng-src="{( comment.image )}" class="img-responsive"/>
        </div>
        <div class="col-lg-9">
            <h2>{( comment.title )}</h2>
            <p>{( comment.description)}</p>
            <div class="beach-detail">
                Spiaggia: {( comment.beach.name)} ({( comment.beach.city)})
            </div>

        </div>

        <div class="clearfix"></div>
        <div class="comment-footer text-right">
            Postato da : {( comment.name )}
        </div>
    </div>

</div>
